--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/KygekTagsShop
build-by-default: true
branches:
- master
projects:
  KygekTagsShop:
    path: ""
    libs:
    - src: Vecnavium/FormsUI/FormsUI
      version: ^1.1.2
    - src: thebigcrafter/ktpmpl-cfs/ktpmpl-cfs
      version: ^1.0
...
