--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KygekTeam/KygekTagsShop
build-by-default: true
branches:
- master
projects:
  KygekTagsShop:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
    - src: thebigcrafter/ktpmpl-cfs/ktpmpl-cfs
      version: ^1.0
...
